# Generated by Django 4.1.7 on 2023-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_tags_uuidtaggeditem_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='f_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='l_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone no.'),
        ),
    ]
